apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-l2n7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-qtkv-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-l2n7@sha256:8d3ad5b004d63177a96c12bbac13098b04f35cd234d85008d416dc9eba0d8434
        name: my-python
        resources: {}
status: {}
